src/routes/main.py
from flask import render_template, redirect, url_for, Blueprint
import database as db
from .helpers import admin_required

bp = Blueprint('main', __name__)


@bp.route('/error')
def error():
    return render_template('error.html', code=str(402), message="You do not have permission to view this page.")


@bp.route('/')
def index():
    return redirect(url_for('music.artist'))


def has_no_empty_params(rule):
    defaults = rule.defaults if rule.defaults is not None else ()
    arguments = rule.arguments if rule.arguments is not None else ()
    return len(defaults) >= len(arguments)


@bp.route('/admin')
@admin_required
def admin():
    import pmv
    routes = sorted([rule for rule in pmv.app.url_map.iter_rules()], key=lambda rule: rule.endpoint)

    return render_template('admin.html', title="Admin", users=db.get_users(), routes=routes)


# ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__',
#         '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__',
#         '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__',
#         '__subclasshook__', '__weakref__', '_argument_weights', '_converters', '_regex', '_static_weights', '_trace',
#         'alias', 'arguments', 'bind', 'build', 'build_compare_key', 'build_only', 'compile', 'defaults', 'empty',
#         'endpoint', 'get_converter', 'get_empty_kwargs', 'get_rules', 'host', 'is_leaf', 'map', 'match',
#         'match_compare_key', 'methods', 'provide_automatic_options', 'provides_defaults_for', 'redirect_to',
#         'refresh', 'rule', 'strict_slashes', 'subdomain', 'suitable_for']

src/routes/music.py
import datetime
import operator
from functools import reduce
from urllib.parse import unquote

from flask import render_template, redirect, url_for, Blueprint, send_file, request, flash, make_response
from magic import Magic

import database as db
from helper import get_current_user
from .helpers import require_permission, get_json_response, wants_html

bp = Blueprint('music', __name__, url_prefix='/music')
al = Blueprint('album', __name__, url_prefix='/music/album')
tr = Blueprint('track', __name__, url_prefix='/music/track')
pl = Blueprint('playlist', __name__, url_prefix='/music/playlist')


@bp.route('/artist')
@bp.route("/artist/<int:artist_id>")
@require_permission(db.Permission.music_can_view)
def artist(artist_id: int = None):
    if artist_id:
        artist = db.get_artist_by_id(artist_id)
        albums = artist.albums
        albums.sort(key=lambda x: x.release_date or datetime.date(datetime.MINYEAR, 1, 1), reverse=True)

        if 'text/html' in request.accept_mimetypes:
            return_data = render_template('table.html', albums=albums, title=artist.name)
        else:
            return_data = get_json_response(albums)
    else:
        artists = db.get_artists()
        artists.sort(key=lambda x: x.name_sort)
        if wants_html():
            return_data = render_template('table.html', artists=artists, title="Artists")
        else:
            return_data = get_json_response(artists)
    return return_data


@al.route("/<int:album_id>")
@require_permission(db.Permission.music_can_view)
def album(album_id: int):
    import pmv
    album = db.get_album_by_id(album_id)
    tracks = album.tracks
    tracks = sorted(tracks, key=lambda x: (x.disc_num, x.track_num))

    if wants_html():
        return render_template('table.html', tracks=tracks, title=album.name, key=album.id, parentKey=album.artist_key,
                               parentTitle=album.artist_name, settings=pmv.settings, totalSize=album.total_size())
    else:
        return get_json_response(tracks)


@tr.route("/<int:track_id>")
def track(track_id: int):
    import images
    import lyrics
    track = db.get_track_by_id(track_id)

    playlists = db.get_playlists_by_user(get_current_user())
    # track.album

    banner_colour = images.get_predominant_colour(track.album)
    button_colour = images.get_button_colour(banner_colour)
    text_colour = images.get_text_colour(banner_colour)

    if wants_html():
        return render_template('track.html', track=track,
                               banner_colour=banner_colour, text_colour=text_colour, button_colour=button_colour,
                               lyrics=lyrics.get_song_lyrics(track)
                               .split('\n'), playlists=playlists)
    else:
        return get_json_response(track, max_depth=1)


@tr.route("/<int:track_id>/file")
@tr.route("/<int:track_id>/file/<download>")
@require_permission(db.Permission.music_can_download)
def track_file(track_id: int, download=False):
    import pmv
    track = db.get_track_by_id(track_id)

    file_path = pmv.settings['music_library'] + unquote(track.download_url)

    mime = Magic(mime=True)
    mimetype = mime.from_file(file_path)

    return send_file(file_path, mimetype=mimetype,
                     as_attachment=download, attachment_filename='%s.%s' % (track.name, track.format))


@pl.route('/')
@require_permission(db.Permission.music_can_view)
def playlists():
    playlists = db.get_playlists_by_user(get_current_user()) or []

    if wants_html():
        return render_template('playlists.html', playlists=playlists)
    else:
        return get_json_response(playlists)


@pl.route('/<int:playlist_id>')
@require_permission(db.Permission.music_can_view)
def playlist(playlist_id: int):
    import pmv
    playlist = db.get_playlist_by_id(playlist_id)

    if wants_html():
        return render_template('table.html', tracks=playlist.tracks, title=playlist.name, settings=pmv.settings,
                               is_playlist=True, key=playlist_id,
                               totalSize=reduce(operator.add, [track.size for track in playlist.tracks]))
    else:
        tracks = [*map(lambda x: x.id, playlist.tracks)]
        return get_json_response(playlist, max_depth=1, append={'tracks': tracks})


@pl.route('/add/<string:name>', methods=['POST'])
@require_permission(db.Permission.music_can_view)
def create_playlist(name: str):
    playlist = db.Playlist(name=name, creator_id=get_current_user().id)
    db.add_single(playlist)

    return redirect(request.referrer)


@pl.route('/<int:playlist_id>/add/<int:track_id>', methods=['POST'])
@pl.route('/<int:playlist_id>/add/<int:track_id>/<string:playlist_name>', methods=['POST'])
@pl.route('/add/<int:track_id>', methods=['POST'])
@pl.route('/add/<int:track_id>/<string:playlist_name>', methods=['POST'])
@require_permission(db.Permission.music_can_view)
def add_to_playlist(track_id: int, playlist_id: int = None, playlist_name: str = None):
    if not playlist_id:
        playlist_id = int(request.form.get('playlist_id'))

    if playlist_id == -1:
        if not playlist_name:
            playlist_name = request.form.get('playlist_name')
        playlist = db.Playlist(name=playlist_name, creator_id=get_current_user().id)
    else:
        playlist = db.get_playlist_by_id(playlist_id)

    track = db.get_track_by_id(track_id)

    # Check track not already in playlist
    f = [*filter(lambda track: track.id == track_id, playlist.tracks)]
    if not f or len(f) == 0:
        playlist.tracks.append(track)
        db.session().commit()

    return redirect(request.referrer)


@tr.route('/<int:track_id>/lyrics', methods=['GET', 'POST'])
@require_permission(db.Permission.music_can_edit)
def lyrics(track_id: int):
    import lyrics
    current_track = db.get_track_by_id(track_id)

    if request.method == "POST":
        lyrics.update_lyrics(current_track, request.form.get('lyrics'))

        flash('Lyrics successfully updated', category='success')
        return redirect(url_for('music.track', track_id=track_id))

    lyrics = lyrics.get_song_lyrics(current_track)
    response = make_response(lyrics, 200)
    response.mimetype = "text/plain"
    return response


@tr.route('/<int:track_id>/metadata', methods=['POST'])
@require_permission(db.Permission.music_can_edit)
def update_metadata(track_id: int):
    print(request.form)
    return str(track_id)  # TODO Write metadata updating (local, database, plex)


@bp.route("/search", methods=['GET', 'POST'])
@bp.route("/search/<query>", methods=['GET', 'POST'])
@require_permission(db.Permission.music_can_view)
def search(query=None, for_artists=True, for_albums=True, for_tracks=True):
    if not query:
        query = request.form.get('query')

    if for_artists:
        artists = db.get_artists_by_name(query)

    if for_albums:
        albums = db.get_albums_by_name(query)

    if for_tracks:
        tracks = db.get_tracks_by_name(query)

    if wants_html():
        return render_template('table.html', artists=artists, albums=albums, tracks=tracks, title=query,
                               is_search=True, prev=request.referrer)
    else:
        return get_json_response({'artists': artists, 'albums': albums, 'tracks': tracks}, max_depth=3)

src/routes/users.py
from json import dumps

from flask import Blueprint, request, redirect, url_for, flash, render_template
from flask_login import login_user, logout_user, login_required
from werkzeug.security import check_password_hash, generate_password_hash
import database as db
from .helpers import admin_required

bp = Blueprint('users', __name__)


@bp.route("/login", methods=['GET', 'POST'])
def login():
    import pmv
    display_flash = False

    if request.method == 'POST':
        username = request.form.get('username').lower()
        password = request.form.get('password')
        remember = request.form.get('remember') is not None
        user = pmv.get_user(username)

        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember)
                return redirect(request.args.get('next') or url_for('main.index'))
            else:
                flash("Incorrect password", category='error')
                display_flash = True
        else:
            flash("Incorrect username", category='error')
            display_flash = True

    return render_template('accounts.html', title="Log in", force_display=display_flash)


@bp.route('/signup', methods=['POST'])
def sign_up():
    import pmv
    username = request.form['username'].lower()
    password = request.form['password']
    remember = request.form.get('remember') is not None

    db.add_user(username, generate_password_hash(password))
    # TODO Add some proper validation, redirecting for signup
    # if len(data) == 0:
    user = pmv.get_user(username)
    login_user(user, remember)
    return redirect(url_for('main.index'))
    # else:
    #   return dumps({'error': str(data[0])})


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@bp.route('/profile')
@login_required
def profile():
    return render_template('profile.html')


@bp.route('/delete_user/<string:username>', methods=['POST', 'DELETE'])
@admin_required
def delete_user(username):
    db.delete_user_by_username(username)
    db.session().commit()

    if request.method == 'POST':
        flash("User '%s' successfully deleted." % username, category='success')
        return redirect(request.referrer)
    else:
        return dumps({'message': 'User %s successfully deleted' % username}) \



@bp.route('/delete_user_by_id/<int:key>', methods=['POST', 'DELETE'])
@admin_required
def delete_user_by_id(key: int, restore=False):
    """
    Marks the user with the given ID as deleted.
    Does not actually delete the user from the database
    so that it is possible to restore them. This also
    allows for hard account suspension.
    :param key: The user ID
    :param restore: If this is set to True, undelete the user.
    :return:
    """
    db.delete_user_by_id(key, restore)

    message = "User with ID %r' successfully %s." % (key, "restored" if restore else 'deleted')
    if request.method == 'POST':
        flash(message, category='success')
        return redirect(request.referrer)
    else:
        return dumps({'message': message})


@admin_required
def restore_user_by_id(key: int):
    """
    Alias for :func:`delete_user_by_id<app.delete_user_by_id>`.
    Restore is passed as True.
    """
    delete_user_by_id(key, True)


# TODO URGENT - Rewrite this to be more dynamic - only update given values
@admin_required
def edit_user_by_id(key: int):
    form = request.form

    db.edit_user_by_id(key, form)

    db.session().commit()

    message = "User with ID %r' successfully edited." % key
    if request.method == 'POST':
        flash(message, category='success')
        return redirect(request.referrer)
    else:
        return dumps({'message': message})


@bp.route('/edit_user', methods=['POST'])
@bp.route('/edit_user/<username>', methods=['POST'])
@admin_required
def edit_user(username=None):  # TODO Add editing by username
    action = request.form.get('action')
    if action:  # If handling an AJAX request from table
        if action == 'edit':
            edit_user_by_id(request.form.get('id'))

        elif action == 'delete':
            delete_user_by_id(request.form.get('id'))

        elif action == 'restore':
            delete_user_by_id(request.form.get('id'), True)

        return dumps(request.form)

src/templates/accounts.html
{% extends "layout.html" %}

{% block head %}
{#    <link rel="stylesheet" href="{{ url_for('static', filename='accounts.css')}}">#}
{% endblock %}

{% block body %}
    {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}

    <div class="row justify-content-md-center">
        <div class="col col-md-4">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="login-tab" data-toggle="tab" href="#login" role="tab" aria-controls="login" aria-selected="true">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="signup-tab" data-toggle="tab" href="#signup" role="tab" aria-controls="signup" aria-selected="false">Signup</a>
              </li>
            </ul>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col col-md-4">
            <div class="tab-content" id="myTabContent">
                <!-- Login -->
                <div class="tab-pane show active" id="login" role="tabpanel" aria-labelledby="login-tab">
                    <form action="{{ url_for('users.login') }}" method=post class="form-signin">
                        <h2 class="form-signin-heading">Sign in</h2>

                        <label for="inputUsername" class="sr-only">Username</label>
                        <input name="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>

                        <label for="inputPassword" class="sr-only">Password</label>
                        <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>

                        <div class="checkbox">
                          <label>
                            <input name="remember" type="checkbox"> Remember me
                          </label>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                    </form>
                </div>
                <!-- Sign up -->
                <div class="tab-pane" id="signup" role="tabpanel" aria-labelledby="signup-tab">
                    <form action="{{ url_for('users.sign_up') }}" method=post class="form-signin">
                        <h2 class="form-signin-heading">Sign up</h2>

                        <label for="inputUsername" class="sr-only">Username</label>
                        <input name='username' id="inputUsername" class="form-control" placeholder="Username" required autofocus>

                        <label for="inputPassword" class="sr-only">Password</label>
                        <input name='password' type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                        <div class="checkbox">
                            <label>
                                <input name="remember" type="checkbox"> Remember me
                            </label>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

src/templates/error.html
{% extends "layout.html" %}

{% block head %}
{#    <link rel="stylesheet" href="{{ url_for('static', filename='error.css')}}">#}
{% endblock %}

{% block body %}
   <div class="row justify-content-md-center">
        <div class="col col-md-7">
            <p>{{ code }} - {{ message }}</p>
        </div>
        <div class="col col-md-5">
{#            <img src="{{ url_for('static', filename='img/%s.png' % code) }}" class="img-fluid" alt="Error">#}
            <img class="img-fluid" src="http://via.placeholder.com/700x500">
        </div>
    </div>
{% endblock %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title + " - " if title else '' }}Media Download</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Media Download</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('music.artist') }}">Music <span class="sr-only">(current)</span></a>
            </li>
            {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="accountDropdown">
                        <a class="dropdown-item" href="{{ url_for('users.profile') }}">Profile</a>
                        <a class="dropdown-item" href="{{ url_for('playlist.playlists') }}">Playlists</a>
                        {% if current_user.is_admin %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('main.admin') }}">Admin area</a>
                        {% endif %}
                    </div>
                </li>
            {% endif %}
        </ul>
        {% if current_user.is_authenticated %}
            <span class="navbar-text">
         Hi {{ current_user.username|title }}
    </span>
            <span class="navbar-text">
            <a class="nav-link" href="{{ url_for('users.logout') }}">Log out</a>
        </span>
        {% endif %}

        <form class="form-inline my-2 my-lg-0 ml-2" action="{{ url_for('music.search') }}" method="post">
            <input name="query" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            {#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
        </form>
    </div>
</nav>
{% block body_before %}{% endblock %}
<div class="container">
    {% if title != 'Log in' or force_display %}
        {% with messages = get_flashed_messages(with_categories=true) %}
            <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <!-- <strong>Title</strong> --> {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    {% endif %}
    {% block body %}{% endblock %}
</div>
<!-- Tabledit requires a full jquery build TODO: Only load full JQuery where required -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>
{% block footer_scripts %}{% endblock %}
</body>
</html>

src/templates/playlists.html
{% extends 'layout.html' %}

{% block body %}
    {% for playlist in playlists %}
        <p><a href="{{ url_for('playlist.playlist', playlist_id=playlist.id) }}">{{playlist.name}}</a></p>
    {% endfor %}
    <hr>
    <a href="{{ url_for('playlist.create_playlist', name="Test Playlist")}}">Create Playlist</a>
{% endblock %}

src/templates/track.html
{% extends "layout.html" %}

{% block head %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css"
          rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/track.css') }}">
{% endblock %}

{% block body_before %}
    <audio id="audio" preload="auto"></audio>
    <div class="jumbotron jumbotron-fluid" style="background-color: {{ banner_colour }}; color: {{ text_colour }}">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-sm-3 album-art">
                    <img alt="{{ track.album_name }}" src="{{ url_for('album.image', album_id=track.album_key, width=200) }}">
                </div>
                <div class="col-12 col-md-9 col-lg-6">
                    <h1 class="display-4">{{ track.track_num }} - {{ track.name }}</h1>
                    <p class="lead">{{ track.artist_name }} - {{ track.album_name }}</p>
                </div>
                <div class="col-12 col-lg-3">
                    <button class="btn btn-round"
                            style="background-color: {{ button_colour }}; color: {{ text_colour }};"
                            onclick="play(`{{ url_for('track.track_file', track_id=track.id) }}`)" title="Play/Pause">
                        <span id="play" class="oi oi-media-play"></span>
                    </button>
                    <a class="btn btn-round" style="background-color: {{ button_colour }}; color: {{ text_colour }};"
                       href="{{ url_for('track.track_file', track_id=track.id, download='download') }}" title="Download">
                        <span class="oi oi-data-transfer-download" style="top: 17%;"></span></a>
                    <a class="btn btn-round" style="background-color: {{ button_colour }}; color: {{ text_colour }};"
                       data-toggle="modal" data-target="#addToPlaylist" title="Add to Playlist">
                        <span class="oi oi-list" style="top: 17%;"></span></a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('music.artist') }}">Artists</a></li>
            <li class="breadcrumb-item"><a
                    href="{{ url_for('music.artist', artist_id=track.artist_key) }}">{{ track.artist_name }}</a></li>
            <li class="breadcrumb-item"><a
                    href="{{ url_for('album.album', album_id=track.album_key) }}">{{ track.album_name }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{ track.name }}</li>
        </ol>
    </nav>
    <h2>Lyrics
        <button class="btn btn-link" data-toggle="modal" data-target="#editLyrics">
            <span class="oi oi-pencil"></span>
        </button>
    </h2>
    <p class="lyrics">
        {% for line in lyrics %}
            {{ line }}<br>
        {% endfor %}
    </p>

    <h2>Metadata</h2>
    <table class="table table-striped" id="metadata_table">
        <tbody>
        <tr>
            <td><b>Title</b></td>
            <td>{{ track.name }}</td>
        </tr>
        <tr>
            <td><b>Sort Title</b></td>
            <td>{{ track.name_sort }}</td>
        </tr>
        <tr>
            <td><b>Artist</b></td>
            <td>{{ track.artist_name }}</td>
        </tr>
        <tr>
            <td><b>Album</b></td>
            <td>{{ track.album_name }}</td>
        </tr>
        <tr>
            <td><b>Track Number</b></td>
            <td>{{ track.track_num }}</td>
        </tr>
        <tr>
            <td><b>Disc Number</b></td>
            <td>{{ track.disc_num }}</td>
        </tr>
        </tbody>
    </table>

    <div class="modal fade" id="editLyrics" tabindex="-1" role="dialog" aria-labelledby="lyricsModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="lyricsModalLabel">Edit Lyrics</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('track.lyrics', track_id=track.id) }}" method="post">
                        <div class="form-group">
                            <!-- Single line formatting must be preserved to format the lyrics inside the texarea correctly. -->
                            <textarea name="lyrics" class="form-control" style="min-width: 100%;"
                                      rows=25>{% for line in lyrics %}{{ line + '\n' }}{% endfor %}</textarea>
                        </div>
                        <hr>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="addToPlaylist" tabindex="-1" role="dialog" aria-labelledby="addToPlaylistLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addToPlaylistLabel">Add to Playlist</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('playlist.add_to_playlist', track_id=track.id) }}" method="post">
                        <div class="form-group">
                            <!-- Single line formatting must be preserved to format the lyrics inside the texarea correctly. -->
                            <label for="selectPlaylist">Select Playlist</label>
                            <select class="form-control" id="selectPlaylist" name="playlist_id">
                                <option value="-1">New playlist...</option>
                                {% for playlist in playlists %}
                                    <option value="{{ playlist.id }}">{{ playlist.name }}</option>
                                {% endfor %}
                            </select>
                            <label for="newPlaylistName">New Playlist Name</label>
                            <input class="form-control" id="newPlaylistName" name="playlist_name"
                                   placeholder="Select 'New playlist...' to create a new playlist">
                        </div>
                        <hr>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_scripts %}
    <script src="{{ url_for('static', filename='js/jquery.tabledit.min.js') }}"></script>
    <script>
        $('#metadata_table').Tabledit({
            url: "{{ url_for('track.update_metadata', track_id=track.id) }}",
            editButton: false,
            deleteButton: false,
            columns: {
                identifier: [0, 'type'],
                editable: [[1, 'metadata']]
            }
        });
    </script>
    <script>
        function baseName(str) {
            let base = String(str).substring(str.lastIndexOf('/') + 1);
            if (base.lastIndexOf(".") != -1)
                base = base.substring(0, base.lastIndexOf("."));
            return base;
        }

        let status = 0;
        let prevID;

        function play(music) {

            let btnID = baseName(music);


            let audio = $("#audio");
            let btn = $(`#play`);

            if (btnID != prevID) {
                status = 0;
                let btns = $('*[id^="play"]').attr("class", "oi oi-media-play");

            }
            prevID = btnID;

            if (status == 0 || status == 2) {
                if (status == 0) audio.attr("src", music);
                audio[0].play();
                btn.attr("class", "oi oi-media-pause");
                status = 1;
            } else if (status == 1) {
                audio[0].pause();
                btn.attr("class", "oi oi-media-play");
                status = 2;
            }
        }
    </script>
{% endblock %}